const SET_PRODUCTS_FROM_API = "SET_PRODUCTS_FROM_API";
const ADD_PRODUCTS_TO_CART = "ADD_PRODUCTS_TO_CART";
const ADD_PRODUCTS_TO_WISHLIST = "ADD_PRODUCTS_TO_WISHLIST";
const UPDATE_PRODUCTS_FROM_API = "UPDATE_PRODUCTS_FROM_API";
const UPDATE_PRODUCTS_CART = "UPDATE_PRODUCTS_CART";
const DELETE_PRODUCTS_FROM_CART = "DELETE_PRODUCTS_FROM_CART";
const DELETE_PRODUCTS_FROM_WISHLIST = "DELETE_PRODUCTS_FROM_WISHLIST";
const CLEAR_ALL_PRODUCTS_FROM_CART = "CLEAR_ALL_PRODUCTS_FROM_CART";
const CHANGE_LAYOUT = "CHANGE_LAYOUT";
// user authentication
const SET_USER_DATA = "SET_USER_DATA";
const CLEAR_USER_DATA = "CLEAR_USER_DATA";
//show sidebar menu
const SHOW_SIDEBAR_MENU = "SHOW_SIDEBAR_MENU";

export default {
  SET_PRODUCTS_FROM_API,
  UPDATE_PRODUCTS_FROM_API,
  UPDATE_PRODUCTS_CART,
  ADD_PRODUCTS_TO_CART,
  ADD_PRODUCTS_TO_WISHLIST,
  DELETE_PRODUCTS_FROM_CART,
  DELETE_PRODUCTS_FROM_WISHLIST,
  CLEAR_ALL_PRODUCTS_FROM_CART,
  CHANGE_LAYOUT,
  SET_USER_DATA,
  CLEAR_USER_DATA,
  SHOW_SIDEBAR_MENU,
};
