const SET_PRODUCTS_FROM_API = "SET_PRODUCTS_FROM_API";
const ADD_PRODUCTS_TO_CART = "ADD_PRODUCTS_TO_CART";
const ADD_PRODUCTS_TO_WISHLIST = "ADD_PRODUCTS_TO_WISHLIST";
const UPDATE_PRODUCTS_FROM_API = "UPDATE_PRODUCTS_FROM_API";
const UPDATE_PRODUCTS_CART = "UPDATE_PRODUCTS_CART";
const DELETE_PRODUCTS_FROM_CART = "DELETE_PRODUCTS_FROM_CART";
const DELETE_PRODUCTS_FROM_WISHLIST = "DELETE_PRODUCTS_FROM_WISHLIST";
const CLEAR_ALL_PRODUCTS_FROM_CART = "CLEAR_ALL_PRODUCTS_FROM_CART";
const CHANGE_LAYOUT = "CHANGE_LAYOUT";

export default {
  SET_PRODUCTS_FROM_API,
  UPDATE_PRODUCTS_FROM_API,
  UPDATE_PRODUCTS_CART,
  ADD_PRODUCTS_TO_CART,
  ADD_PRODUCTS_TO_WISHLIST,
  DELETE_PRODUCTS_FROM_CART,
  DELETE_PRODUCTS_FROM_WISHLIST,
  CLEAR_ALL_PRODUCTS_FROM_CART,
  CHANGE_LAYOUT,
};
