const SET_PRODUCTS_FROM_API = "SET_PRODUCTS_FROM_API";
const ADD_PRODUCTS_TO_CART = "ADD_PRODUCTS_TO_CART";
const ADD_PRODUCTS_TO_WISHLIST = "ADD_PRODUCTS_TO_WISHLIST";

export default {
  SET_PRODUCTS_FROM_API,
  ADD_PRODUCTS_TO_CART,
  ADD_PRODUCTS_TO_WISHLIST,
};
